El/plat 767 implement storage and extrinsics
ajuna-network/Ajuna pull request #248
Opened 2023-04-04 10:41 UTC by cowboy-bebug

## Description

Re: [PLAT-767](https://ajunanetwork.atlassian.net/browse/PLAT-767)

## Type of changes

- [ ] `build`: Changes that affect the build system or external dependencies (eg, Cargo, Docker)
- [ ] `ci`: Changes to CI configuration
- [ ] `docs`: Changes to documentation only
- [ ] `feat`: Changes to add a new feature
- [ ] `fix`: Changes to fix a bug
- [ ] `refactor`: Changes that do not alter functionality
- [ ] `style`: Changes to format the code
- [ ] `test`: Changes to add missing tests or correct existing tests

## Checklist

- [ ] Tests for the changes have been added
- [ ] Necessary documentation is added (if appropriate)
- [ ] Formatted with `cargo fmt --all`
- [ ] Linted with `cargo clippy --all-features --all-targets`
- [ ] Tested with `cargo test --workspace --all-features --all-targets`

2023-04-04 17:20 UTC, darkfriend77 requested changes
frozen state and prepare_avatar seem to be redundant?
avatars can still be changed when in prepare_avatar storage?
proper cleanup when nft is created is missing?
prepare_fee properly taken?

2023-04-04 19:51 UTC, cowboy-bebug commented on pallets/ajuna-awesome-avatars/src/lib.rs
👍 addressed in https://github.com/ajuna-network/Ajuna/pull/250

2023-04-04 19:52 UTC, cowboy-bebug commented on pallets/ajuna-awesome-avatars/src/lib.rs
>  			T::NftHandler::store_as_nft(player, collection_id, avatar_id, avatar)?;
👍 addressed in https://github.com/ajuna-network/Ajuna/pull/250

2023-04-04 20:45 UTC, cowboy-bebug commented on pallets/ajuna-awesome-avatars/src/tests.rs
👍 addressed in https://github.com/ajuna-network/Ajuna/pull/250

2023-04-04 20:45 UTC, cowboy-bebug commented on pallets/ajuna-awesome-avatars/src/tests.rs
https://github.com/ajuna-network/Ajuna/pull/250/files

2023-04-04 21:19 UTC, cowboy-bebug commented on pallets/ajuna-awesome-avatars/src/lib.rs
>  			T::NftHandler::store_as_nft(player, collection_id, avatar_id, avatar)?;
Created a follow up task [PLAT-781](https://ajunanetwork.atlassian.net/browse/PLAT-781)

2023-04-05 06:28 UTC, darkfriend77 submitted a review, later dismissed
nice!

2023-04-05 23:49 UTC, merged